
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 15 16:30:23 BTT 2021
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 3;
  public static final int error = 1;
  public static final int CPAREN = 5;
  public static final int PLUS = 2;
  public static final int NUMBER = 6;
  public static final int OPAREN = 4;
  public static final int EOF = 0;
}

