/* The following code was generated by JFlex 1.4_pre3 on 5/15/21 3:36 PM */

/* --------------------------UserCode Section------------------------ */
/* Used to generate tokens from input string. */

package src;
import java_cup.runtime.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4_pre3
 * on 5/15/21 3:36 PM from the specification file
 * <tt>file:/C:/Users/Younten Tshering/Desktop/PLC group work/PLC_Project_Final/src/flex/lcalc.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int YY_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  2,  0,  3,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     8, 30,  0,  9,  9, 24, 33, 10, 28, 29, 22, 20, 26, 21,  6, 23, 
     4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  0, 25, 31, 27, 32,  0, 
     9,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 
     7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  0,  0,  0,  9, 19, 
     0, 16, 38,  7, 40, 14, 15, 39, 42, 35,  7,  7, 17,  7, 36, 37, 
    45,  7, 12, 18, 11, 13,  7, 41,  7,  7,  7, 43, 34, 44,  0,  0
  };


  /** 
   * Translates a state to a row index in the transition table (packed version)
   */
  final private static String yy_rowMap_packed = 
    "\0\0\0\56\0\134\0\56\0\212\0\270\0\346\0\u0114\0\u0142\0\u0170"+
    "\0\u019e\0\u01cc\0\56\0\56\0\56\0\56\0\56\0\56\0\56\0\u01fa"+
    "\0\56\0\56\0\u0228\0\u0256\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a"+
    "\0\56\0\56\0\u0398\0\212\0\u03c6\0\u03f4\0\u0114\0\u0422\0\56\0\u0450"+
    "\0\u047e\0\u04ac\0\u04da\0\u0508\0\u0536\0\56\0\56\0\56\0\56\0\56"+
    "\0\56\0\346\0\u0564\0\u0592\0\u05c0\0\u05ee\0\u03c6\0\u061c\0\u064a\0\u0678"+
    "\0\u06a6\0\u06d4\0\u0702\0\346\0\u0730\0\u075e\0\u078c\0\346\0\346\0\u07ba"+
    "\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\346\0\346\0\u08ce\0\u08fc\0\346"+
    "\0\u092a\0\346\0\u0958\0\u0986\0\346\0\346";

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int [] yy_rowMap = yy_unpack_rowMap(yy_rowMap_packed);


  /** 
   * Unpacks the compressed row translation table.
   *
   * @param packed   the packed row translation table
   * @return         the unpacked row translation table
   */
  private static int [] yy_unpack_rowMap(String packed) {
    int [] map = new int[172];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int high = ((int) packed.charAt(i++)) << 16;
      map[j++] = high | packed.charAt(i++);
    }
    return map;
  }
  /** 
   * The packed transition table of the DFA (part 0)
   */
  private static final String yy_packed0 = 
    "\1\2\1\3\2\4\1\5\1\6\1\2\1\7\1\4"+
    "\1\2\1\10\1\11\2\7\1\12\1\13\2\7\1\14"+
    "\1\7\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\2\7\1\35\2\7\1\36\1\7\1\37\1\40"+
    "\1\41\60\0\1\4\57\0\2\42\1\43\53\0\2\6"+
    "\1\43\53\0\2\7\1\0\1\7\3\0\11\7\17\0"+
    "\10\7\2\0\1\7\4\0\2\44\1\0\2\45\1\46"+
    "\1\47\10\45\3\0\1\46\1\0\1\46\3\0\3\46"+
    "\2\0\2\46\10\45\2\0\1\45\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\1\50\7\7\17\0\10\7\2\0"+
    "\1\7\4\0\2\7\1\0\1\7\3\0\6\7\1\51"+
    "\2\7\17\0\1\7\1\52\6\7\2\0\1\7\4\0"+
    "\2\7\1\0\1\7\3\0\5\7\1\53\1\54\2\7"+
    "\17\0\10\7\2\0\1\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\55\10\7\17\0\10\7\2\0\1\7\33\0"+
    "\1\56\55\0\1\57\55\0\1\60\55\0\1\61\63\0"+
    "\1\62\56\0\1\63\17\0\2\7\1\0\1\7\3\0"+
    "\4\7\1\64\4\7\17\0\1\7\1\65\6\7\2\0"+
    "\1\7\4\0\2\7\1\0\1\7\3\0\11\7\17\0"+
    "\2\7\1\66\5\7\2\0\1\7\4\0\2\7\1\0"+
    "\1\7\3\0\11\7\17\0\7\7\1\67\2\0\1\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\1\70\7\7"+
    "\17\0\10\7\2\0\1\7\4\0\2\71\54\0\2\44"+
    "\4\0\1\47\47\0\2\44\3\0\1\46\1\47\13\0"+
    "\1\46\1\0\1\46\3\0\3\46\2\0\2\46\17\0"+
    "\2\7\1\0\1\7\3\0\2\7\1\72\6\7\17\0"+
    "\10\7\2\0\1\7\4\0\2\7\1\0\1\7\3\0"+
    "\7\7\1\73\1\7\17\0\10\7\2\0\1\7\4\0"+
    "\2\7\1\0\1\7\3\0\11\7\17\0\5\7\1\74"+
    "\2\7\2\0\1\7\4\0\2\7\1\0\1\7\3\0"+
    "\6\7\1\75\2\7\17\0\10\7\2\0\1\7\4\0"+
    "\2\7\1\0\1\7\3\0\11\7\17\0\2\7\1\76"+
    "\5\7\2\0\1\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\1\77\7\7\17\0\10\7\2\0\1\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\100\10\7\17\0\10\7"+
    "\2\0\1\7\4\0\2\7\1\0\1\7\3\0\11\7"+
    "\17\0\2\7\1\101\5\7\2\0\1\7\4\0\2\7"+
    "\1\0\1\7\3\0\11\7\17\0\1\102\7\7\2\0"+
    "\1\7\4\0\2\7\1\0\1\7\3\0\11\7\17\0"+
    "\1\103\7\7\2\0\1\7\4\0\2\7\1\0\1\7"+
    "\3\0\3\7\1\104\5\7\17\0\10\7\2\0\1\7"+
    "\4\0\2\7\1\0\1\7\3\0\3\7\1\105\5\7"+
    "\17\0\10\7\2\0\1\7\4\0\2\7\1\0\1\7"+
    "\3\0\11\7\17\0\1\106\7\7\2\0\1\7\4\0"+
    "\2\7\1\0\1\7\3\0\7\7\1\72\1\7\17\0"+
    "\10\7\2\0\1\7\4\0\2\7\1\0\1\7\3\0"+
    "\5\7\1\107\3\7\17\0\10\7\2\0\1\7\4\0"+
    "\2\7\1\0\1\7\3\0\11\7\17\0\1\110\7\7"+
    "\2\0\1\7\4\0\2\7\1\0\1\7\3\0\6\7"+
    "\1\111\2\7\17\0\10\7\2\0\1\7\4\0\2\7"+
    "\1\0\1\7\3\0\6\7\1\112\2\7\17\0\10\7"+
    "\2\0\1\7\4\0\2\7\1\0\1\7\3\0\11\7"+
    "\17\0\1\7\1\113\6\7\2\0\1\7\4\0\2\7"+
    "\1\0\1\7\3\0\4\7\1\114\4\7\17\0\10\7"+
    "\2\0\1\7\4\0\2\7\1\0\1\7\3\0\1\115"+
    "\10\7\17\0\10\7\2\0\1\7\4\0\2\7\1\0"+
    "\1\7\3\0\11\7\17\0\1\7\1\116\6\7\2\0"+
    "\1\7\4\0\2\7\1\0\1\7\3\0\3\7\1\117"+
    "\5\7\17\0\10\7\2\0\1\7\4\0\2\7\1\0"+
    "\1\7\3\0\3\7\1\120\5\7\17\0\10\7\2\0"+
    "\1\7\4\0\2\7\1\0\1\7\3\0\1\121\10\7"+
    "\17\0\10\7\2\0\1\7\4\0\2\7\1\0\1\7"+
    "\3\0\11\7\17\0\4\7\1\122\3\7\2\0\1\7"+
    "\4\0\2\7\1\0\1\7\3\0\5\7\1\123\3\7"+
    "\17\0\10\7\2\0\1\7\4\0\2\7\1\0\1\7"+
    "\3\0\6\7\1\124\2\7\17\0\10\7\2\0\1\7"+
    "\4\0\2\7\1\0\1\7\3\0\11\7\17\0\1\7"+
    "\1\125\6\7\2\0\1\7\4\0\2\7\1\0\1\7"+
    "\3\0\11\7\17\0\1\7\1\126\6\7\2\0\1\7";

  /** 
   * The transition table of the DFA
   */
  private static final int yytrans [] = yy_unpack();


  /* error codes */
  private static final int YY_UNKNOWN_ERROR = 0;
  private static final int YY_ILLEGAL_STATE = 1;
  private static final int YY_NO_MATCH = 2;
  private static final int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  private static final String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final byte YY_ATTRIBUTE[] = {
     0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9, 
     9,  9,  9,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9, 
     1,  0,  0,  0,  0,  0,  9,  1,  1,  1,  1,  1,  1,  9,  9,  9, 
     9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }

    private void debug(String type){
        if(type == "SEPARATOR")
            System.out.println("<"+type+">");
        else
            System.out.print("<"+type+">");
    } 

    private void debug(String type, String text){
        System.out.print("<"+type+","+text+">");
    } 


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2484];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 2: 
        case 3: 
          {  /* just skip what was found, do nothing */  }
        case 87: break;
        case 6: 
        case 8: 
        case 9: 
        case 10: 
        case 11: 
        case 27: 
        case 28: 
        case 29: 
        case 32: 
        case 39: 
        case 40: 
        case 41: 
        case 42: 
        case 43: 
        case 44: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 64: 
        case 65: 
        case 66: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 77: 
        case 78: 
        case 82: 
        case 83: 
          {  
        Integer n = (Integer) SymbolTable.table.get(yytext());
        if (n == null) {
            SymbolTable.table.put(yytext(), 0);
        }
        debug("VAR", yytext() ); 
        return symbol(sym.VAR, yytext()); 
     }
        case 88: break;
        case 67: 
          {  debug("BOOL_LITERAL",yytext()); return symbol(sym.BOL, new Boolean(yytext()));  }
        case 89: break;
        case 85: 
          {  debug("PRINTLN"); return symbol(sym.PRINTLN);  }
        case 90: break;
        case 84: 
          {  debug("BOOL"); return symbol(sym.BOOL);  }
        case 91: break;
        case 30: 
          {  debug("BEGIN"); return symbol(sym.BEGIN);  }
        case 92: break;
        case 24: 
          {  debug("GT"); return symbol(sym.GT);  }
        case 93: break;
        case 23: 
          {  debug("LT"); return symbol(sym.LT);  }
        case 94: break;
        case 21: 
          {  debug("RPAREN"); return symbol(sym.RPAREN);  }
        case 95: break;
        case 20: 
          {  debug("LPAREN"); return symbol(sym.LPAREN);  }
        case 96: break;
        case 19: 
          {  debug("EQUALS"); return symbol(sym.EQUALS);  }
        case 97: break;
        case 18: 
          {  debug("COMMA"); return symbol(sym.COMMA);  }
        case 98: break;
        case 17: 
          {  debug("SEMI"); return symbol(sym.SEMI);  }
        case 99: break;
        case 16: 
          {  debug("MOD");  return symbol(sym.MOD);  }
        case 100: break;
        case 12: 
          {  debug("PLUS");  return symbol(sym.PLUS);  }
        case 101: break;
        case 13: 
          {  debug("MINUS"); return symbol(sym.MINUS);  }
        case 102: break;
        case 14: 
          {  debug("TIMES"); return symbol(sym.TIMES);  }
        case 103: break;
        case 15: 
          {  debug("DIVIDE"); return symbol(sym.DIVIDE);  }
        case 104: break;
        case 31: 
          {  debug("END"); return symbol(sym.END);  }
        case 105: break;
        case 45: 
          {  debug("ET"); return symbol(sym.ET);  }
        case 106: break;
        case 46: 
          {  debug("NET"); return symbol(sym.NET);  }
        case 107: break;
        case 47: 
          {  debug("LTE"); return symbol(sym.LTE);  }
        case 108: break;
        case 48: 
          {  debug("GTE"); return symbol(sym.GTE);  }
        case 109: break;
        case 49: 
          {  debug("AND"); return symbol(sym.AND);  }
        case 110: break;
        case 50: 
          {  debug("OR"); return symbol(sym.OR);  }
        case 111: break;
        case 51: 
          {  debug("IF"); return symbol(sym.IF);  }
        case 112: break;
        case 63: 
          {  debug("INT"); return symbol(sym.INT);  }
        case 113: break;
        case 68: 
          {  debug("ELSE"); return symbol(sym.ELSE);  }
        case 114: break;
        case 75: 
          {  debug("ENDIF"); return symbol(sym.ENDIF);  }
        case 115: break;
        case 76: 
          {  debug("FLOAT"); return symbol(sym.FLOAT);  }
        case 116: break;
        case 79: 
          {  debug("WHILE"); return symbol(sym.WHILE);  }
        case 117: break;
        case 80: 
          {  debug("PRINT"); return symbol(sym.PRINT);  }
        case 118: break;
        case 81: 
          {  debug("STRING"); return symbol(sym.STRING);  }
        case 119: break;
        case 4: 
        case 5: 
          {  debug("INT_LITERAL",yytext()); return symbol(sym.INT_LITERAL, new Integer(yytext()));  }
        case 120: break;
        case 38: 
          {  debug("STRING_LITERAL",yytext()); return symbol(sym.STRING_LITERAL, new String(yytext()));  }
        case 121: break;
        case 1: 
        case 7: 
        case 22: 
        case 25: 
        case 26: 
          {  throw new Error("Illegal character <"+yytext()+">");  }
        case 122: break;
        case 56: 
          {  debug("FLOAT_LITERAL",yytext()); return symbol(sym.FLOAT_LITERAL, new Float(yytext()));  }
        case 123: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
