
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 15 15:36:01 ICT 2021
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int STRING_LITERAL = 34;
  public static final int LTE = 15;
  public static final int EQUALS = 9;
  public static final int LPAREN = 10;
  public static final int SEMI = 7;
  public static final int INT = 20;
  public static final int PRINTLN = 29;
  public static final int MINUS = 3;
  public static final int RPAREN = 11;
  public static final int AND = 18;
  public static final int LT = 14;
  public static final int OR = 19;
  public static final int BOOL = 22;
  public static final int COMMA = 8;
  public static final int BEGIN = 30;
  public static final int PLUS = 2;
  public static final int IF = 24;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NET = 13;
  public static final int MOD = 6;
  public static final int ET = 12;
  public static final int GTE = 17;
  public static final int TIMES = 4;
  public static final int ENDIF = 25;
  public static final int ELSE = 26;
  public static final int WHILE = 27;
  public static final int BOL = 35;
  public static final int FLOAT = 21;
  public static final int END = 31;
  public static final int STRING = 23;
  public static final int FLOAT_LITERAL = 33;
  public static final int GT = 16;
  public static final int VAR = 36;
  public static final int PRINT = 28;
  public static final int INT_LITERAL = 32;
}

