/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.concurrent.TimeUnit;
import javax.swing.JTextPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import src.ConsoleOutput.OutputType;

/**
 *
 * @author Younten
 */
public class UI extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        // Initial States of buttons
        btnRun.setEnabled(false);
        //btnReset.setEnabled(false);
        
        // Change button states on change in text area
        taCodeEditor.getDocument().addDocumentListener(new DocumentListener() {
            
            @Override
            public void changedUpdate(DocumentEvent e) {
                btnRun.setEnabled(!taCodeEditor.getText().isEmpty());
                //btnReset.setEnabled(!taCodeEditor.getText().isEmpty());
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                btnRun.setEnabled(!taCodeEditor.getText().isEmpty());
                //btnReset.setEnabled(!taCodeEditor.getText().isEmpty());
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                btnRun.setEnabled(!taCodeEditor.getText().isEmpty());
                //btnReset.setEnabled(!taCodeEditor.getText().isEmpty());
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        merolPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCodeEditor = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taConsole = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnRun = new javax.swing.JButton();
        btnConsole = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Final PLC Project  - Group Work");
        setAlwaysOnTop(true);
        setResizable(false);

        titlePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        titleLabel.setBackground(new java.awt.Color(170, 205, 239));
        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("PLC Project - Basic Programming Language ");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titleLabel)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        merolPanel.setLayout(null);

        taCodeEditor.setBackground(new java.awt.Color(170, 205, 239));
        taCodeEditor.setColumns(20);
        taCodeEditor.setRows(5);
        taCodeEditor.setTabSize(2);
        jScrollPane1.setViewportView(taCodeEditor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        merolPanel.add(jPanel1);
        jPanel1.setBounds(10, 40, 250, 320);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("User Input");
        merolPanel.add(jLabel1);
        jLabel1.setBounds(10, 7, 240, 40);

        taConsole.setEditable(false);
        taConsole.setBackground(new java.awt.Color(170, 205, 239));
        taConsole.setColumns(20);
        taConsole.setLineWrap(true);
        taConsole.setRows(5);
        taConsole.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taConsole);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        merolPanel.add(jPanel2);
        jPanel2.setBounds(300, 40, 250, 320);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Output Console");
        merolPanel.add(jLabel3);
        jLabel3.setBounds(310, 10, 170, 40);

        btnRun.setBackground(new java.awt.Color(157, 250, 12));
        btnRun.setText("Run Input");
        btnRun.addActionListener(this);
        merolPanel.add(btnRun);
        btnRun.setBounds(10, 360, 100, 50);

        btnConsole.setBackground(new java.awt.Color(244, 109, 10));
        btnConsole.setText("Clear Console");
        btnConsole.addActionListener(this);
        merolPanel.add(btnConsole);
        btnConsole.setBounds(420, 360, 130, 50);

        btnReset.setBackground(new java.awt.Color(220, 126, 16));
        btnReset.setText("Reset Input Output");
        btnReset.addActionListener(this);
        merolPanel.add(btnReset);
        btnReset.setBounds(190, 360, 170, 50);

        jLayeredPane1.add(merolPanel, "card4");
        merolPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btnRun) {
            UI.this.btnRunActionPerformed(evt);
        }
        else if (evt.getSource() == btnConsole) {
            UI.this.btnConsoleActionPerformed(evt);
        }
        else if (evt.getSource() == btnReset) {
            UI.this.btnResetActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents


    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRunActionPerformed
        reset();
        runParser();
    }// GEN-LAST:event_btnRunActionPerformed

    private void btnConsoleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsoleActionPerformed
        // Clear the console text area
        taConsole.setText(null);
        ConsoleOutput.getInstance().clear();
    }// GEN-LAST:event_btnConsoleActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
        // Reset all environment tables and variable arrays and symboltable
        reset();

        taCodeEditor.setText(null);
        ConsoleOutput.getInstance().setText("");
        
        // Initialize new items (Type)
    }// GEN-LAST:event_btnResetActionPerformed

    private void setWindowTitle(String title) {
        titleLabel.setText(title);
    }

    private void runParser() {
        /* Start the parser */
        try {
            String program = taCodeEditor.getText();
            InputStream targetStream = new ByteArrayInputStream(program.getBytes());

            Lexer lexer = new Lexer(targetStream);

            MyCUP cup = new MyCUP(lexer);
            cup.parse();
            
            TimeUnit.SECONDS.sleep((long) 0.5);
            
            setConsoleText(ConsoleOutput.getInstance().getText(), ConsoleOutput.getInstance().getOutputType());
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getLocalizedMessage());
            System.out.println(e.getMessage());
            ConsoleOutput.getInstance().setText(e.getLocalizedMessage(), OutputType.ERROR);
            setConsoleText(ConsoleOutput.getInstance().getText(), ConsoleOutput.getInstance().getOutputType());
        } catch (Error e) {
            System.out.println("Catching error");
            System.out.println(e.getLocalizedMessage());
            ConsoleOutput.getInstance().setText(e.getLocalizedMessage(), OutputType.ERROR);
            setConsoleText(ConsoleOutput.getInstance().getText(), ConsoleOutput.getInstance().getOutputType());
        }
    }

    // Reset to Initial State
    private void reset() {
        // Clear Environment Tables and Variable lists
        Environment.table.clear();
        Variables.list.clear();
        
        // Clear Console text
        setConsoleText("", OutputType.OUTPUT);
        ConsoleOutput.getInstance().clear();

    }

    // Set text to console text area and change the color according to output type
    public void setConsoleText(String text, OutputType type) {
        taConsole.setText(text);
        switch (type) {
            case OUTPUT:
                taConsole.setForeground(Color.black);
                break;
                
            case ERROR:
                taConsole.setForeground(Color.red);
                break;
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnConsole;
    javax.swing.JButton btnReset;
    javax.swing.JButton btnRun;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel3;
    javax.swing.JLayeredPane jLayeredPane1;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JPanel merolPanel;
    javax.swing.JTextArea taCodeEditor;
    javax.swing.JTextArea taConsole;
    javax.swing.JLabel titleLabel;
    javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
